### PR TITLE
Update to latest protocol

### PR DESCRIPTION
**Pull request by let-def**
We are preparing for the next release of Merlin.
This one brings support for OCaml 4.03.

The protocol was updated in a non-backward compatible way. This pull request fix the sublime-text mode.

### CODE REVIEW

**Comment by cynddl** [comment]
Thanks! I quickly looked at your code; I assume the implementation of `send_query` is not retro-compatible with previous versions of Merlin?

**Comment by let-def** [comment]
No it is not. But thinking about it, it should be possible to make a compatible version.
I will look at that tomorrow.

**Comment by let-def** [comment]
Done, this version should work with all ocamlmerlin binaries.

**Comment by let-def** [comment]
If you think you have time to review this PR shortly, I would like it to be merged before sending an announcement mail.
Otherwise, I will make the announcement noting that sublime text support will be ready later but that early adopters can try this version.
Sorry to insist :).

**Comment by cynddl** [comment]
Done. And thanks for the pull request and especially the support for older protocols!

**Pull request merged**
